"""
Django settings for superappbeta project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2&wo6=&3040vxi38ygt2jd%dz!qe7q57+$0rj34g&iiab(l84#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 开发时设为 True

# 生产环境设置 (部署时使用)
# DEBUG = False
# ALLOWED_HOSTS = ['your-domain.com', 'www.your-domain.com', 'localhost', '127.0.0.1']

ALLOWED_HOSTS = ['*']  # 开发时允许所有主机

# 安全设置
SECURE_SSL_REDIRECT = False  # 开发时设为 False
SESSION_COOKIE_SECURE = False  # 开发时设为 False
CSRF_COOKIE_SECURE = False  # 开发时设为 False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'files.apps.FilesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # 添加语言支持
]

ROOT_URLCONF = 'superappbeta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'superappbeta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'accounts.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# 添加 STATIC_ROOT 配置
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 确保目录存在
os.makedirs(STATIC_ROOT, exist_ok=True)
os.makedirs(MEDIA_ROOT, exist_ok=True)

# 确保用户上传目录存在
USERS_UPLOAD_ROOT = MEDIA_ROOT / 'users'
os.makedirs(USERS_UPLOAD_ROOT, exist_ok=True)

# 允许上传的文件类型
ALLOWED_FILE_TYPES = {
    'image': ['jpg', 'jpeg', 'png', 'gif'],
    'document': ['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx'],
    'video': ['mp4', 'avi', 'mov', 'wmv'],  # 添加更多视频格式
    'other': ['zip', 'rar', '7z']
}

# 最大文件上传大小 (10MB)
MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# 用户存储空间限制 (100MB)
MAX_USER_STORAGE = 100 * 1024 * 1024

# 单个文件类型的数量限制
MAX_FILES_PER_TYPE = {
    'image': 50,
    'document': 30,
    'video': 10,
    'other': 20
}

# 文件预览设置
PREVIEW_IMAGE_SIZE = (800, 600)  # 图片预览最大尺寸
PREVIEW_VIDEO_LENGTH = 60  # 视频预览最大时长（秒）

# 文件上传配置
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_TEMP_DIR = '/tmp'
FILE_UPLOAD_PERMISSIONS = 0o644

# 会话配置
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2周
SESSION_COOKIE_SECURE = False  # 开发环境设为False

# 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# 登录设置
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'welcome'

# 文件权限设置
FILE_UPLOAD_PERMISSIONS = 0o644
MEDIA_ROOT_PERMISSIONS = 0o755

# 数据库迁移相关设置
MIGRATION_MODULES = {
    'accounts': 'accounts.migrations',
}
