# Generated by Django 5.1.5 on 2025-01-28 11:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像', null=True, upload_to=accounts.models.CustomUser.get_avatar_upload_path, verbose_name='头像'),
        ),
    ]
