# Generated by Django 5.1.5 on 2025-01-30 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, default='13800000000', help_text='请输入11位手机号码，例如：13800138000', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码（11位数字，以1开头）', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
    ]
