# Generated by Django 5.1.5 on 2025-01-31 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='请输入生日，格式：YYYY-MM-DD', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='请输入11位手机号码，例如：13800138000', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码（11位数字，以1开头）', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(blank=True, help_text='请输入您的真实姓名', max_length=50, verbose_name='真实姓名'),
        ),
    ]
