# Generated by Django 5.1.5 on 2025-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_accounts_cu_usernam_ab560e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='用户注册时的IP地址', null=True, verbose_name='注册IP'),
        ),
    ]
