# Generated by Django 5.1.5 on 2025-01-30 03:42

import django.core.validators
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_userstoragequota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=files.models.UserFile.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[])]),
        ),
    ]
