# Generated by Django 5.1.5 on 2025-01-31 06:12

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_userfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=files.models.UserFile.get_upload_path),
        ),
    ]
